[build]
  command = "npm run build && cd backend && composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  PHP_VERSION = "8.2"
  COMPOSER_VERSION = "2.6"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  directory = "backend/public"
  node_bundler = "esbuild" 