[build]
  base = "."
  command = "chmod +x netlify/build.sh && ./netlify/build.sh"
  publish = ".next"
  timeout = 900

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  PHP_VERSION = "8.2"
  COMPOSER_VERSION = "2.6"
  NODE_VERSION = "18"
  LARAVEL_ENV = "production"
  APP_ENV = "production"
  APP_DEBUG = "false"
  COMPOSER_ALLOW_SUPERUSER = "1"
  COMPOSER_HOME = "/opt/buildhome/.composer"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_USE_PACKAGE_LOCK = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true 