<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Mountain Bike Pro',
                'description' => 'Professional mountain bike perfect for off-road adventures. Features high-quality suspension and durable frame.',
                'price' => 899.99,
                'images' => ['/products/Mountain_Bike.png'],
                'category' => 'Mountain Bikes',
                'stock' => 15,
                'featured' => true,
                'sku' => 'MTB-001',
                'weight' => 12.5,
                'dimensions' => ['length' => 180, 'width' => 70, 'height' => 110],
                'brand' => 'BikeYard',
                'model' => 'Pro Mountain',
                'year' => 2024,
                'condition' => 'new',
                'warranty' => '2 years',
                'shipping_info' => 'Free shipping on orders over $500',
            ],
            [
                'name' => 'Road Bike Elite',
                'description' => 'Lightweight road bike built for speed and efficiency. Perfect for racing and long-distance cycling.',
                'price' => 1299.99,
                'images' => ['/products/Road_Bike.png'],
                'category' => 'Road Bikes',
                'stock' => 10,
                'featured' => true,
                'sku' => 'RB-001',
                'weight' => 8.2,
                'dimensions' => ['length' => 175, 'width' => 65, 'height' => 105],
                'brand' => 'BikeYard',
                'model' => 'Elite Road',
                'year' => 2024,
                'condition' => 'new',
                'warranty' => '3 years',
                'shipping_info' => 'Free shipping on orders over $500',
            ],
            [
                'name' => 'Bike Accessories Kit',
                'description' => 'Essential gear for every cyclist. Includes helmet, lights, lock, and basic tools.',
                'price' => 149.99,
                'images' => ['/products/Accessories.png'],
                'category' => 'Accessories',
                'stock' => 50,
                'featured' => true,
                'sku' => 'ACC-001',
                'weight' => 2.1,
                'dimensions' => ['length' => 30, 'width' => 20, 'height' => 15],
                'brand' => 'BikeYard',
                'model' => 'Essential Kit',
                'year' => 2024,
                'condition' => 'new',
                'warranty' => '1 year',
                'shipping_info' => 'Standard shipping',
            ],
            [
                'name' => 'Electric Bike City',
                'description' => 'Eco-friendly electric bike perfect for city commuting. Long battery life and comfortable ride.',
                'price' => 2499.99,
                'images' => ['/products/Mountain_Bike.png'],
                'category' => 'Electric Bikes',
                'stock' => 8,
                'featured' => false,
                'sku' => 'EB-001',
                'weight' => 22.0,
                'dimensions' => ['length' => 185, 'width' => 75, 'height' => 115],
                'brand' => 'BikeYard',
                'model' => 'City Electric',
                'year' => 2024,
                'condition' => 'new',
                'warranty' => '2 years',
                'shipping_info' => 'Free shipping on orders over $500',
            ],
            [
                'name' => 'BMX Freestyle',
                'description' => 'Durable BMX bike designed for tricks and stunts. Strong frame and responsive handling.',
                'price' => 399.99,
                'images' => ['/products/Road_Bike.png'],
                'category' => 'BMX Bikes',
                'stock' => 12,
                'featured' => false,
                'sku' => 'BMX-001',
                'weight' => 11.8,
                'dimensions' => ['length' => 160, 'width' => 60, 'height' => 100],
                'brand' => 'BikeYard',
                'model' => 'Freestyle',
                'year' => 2024,
                'condition' => 'new',
                'warranty' => '1 year',
                'shipping_info' => 'Standard shipping',
            ],
            [
                'name' => 'Cycling Helmet',
                'description' => 'Safety-certified cycling helmet with adjustable fit and ventilation system.',
                'price' => 79.99,
                'images' => ['/products/Accessories.png'],
                'category' => 'Accessories',
                'stock' => 25,
                'featured' => false,
                'sku' => 'ACC-002',
                'weight' => 0.4,
                'dimensions' => ['length' => 25, 'width' => 20, 'height' => 15],
                'brand' => 'BikeYard',
                'model' => 'Safety Pro',
                'year' => 2024,
                'condition' => 'new',
                'warranty' => '1 year',
                'shipping_info' => 'Standard shipping',
            ],
            [
                'name' => 'Bike Lock Set',
                'description' => 'High-security bike lock with cable and mounting bracket. Protects your investment.',
                'price' => 49.99,
                'images' => ['/products/Accessories.png'],
                'category' => 'Accessories',
                'stock' => 30,
                'featured' => false,
                'sku' => 'ACC-003',
                'weight' => 0.8,
                'dimensions' => ['length' => 40, 'width' => 5, 'height' => 5],
                'brand' => 'BikeYard',
                'model' => 'Security Plus',
                'year' => 2024,
                'condition' => 'new',
                'warranty' => '1 year',
                'shipping_info' => 'Standard shipping',
            ],
            [
                'name' => 'Bike Pump',
                'description' => 'Professional bike pump with pressure gauge. Works with all valve types.',
                'price' => 29.99,
                'images' => ['/products/Accessories.png'],
                'category' => 'Accessories',
                'stock' => 20,
                'featured' => false,
                'sku' => 'ACC-004',
                'weight' => 0.6,
                'dimensions' => ['length' => 35, 'width' => 8, 'height' => 8],
                'brand' => 'BikeYard',
                'model' => 'Pro Pump',
                'year' => 2024,
                'condition' => 'new',
                'warranty' => '1 year',
                'shipping_info' => 'Standard shipping',
            ],
            [
                'name' => 'Cycling Jersey',
                'description' => 'Moisture-wicking cycling jersey with breathable fabric and comfortable fit.',
                'price' => 59.99,
                'images' => ['/products/Accessories.png'],
                'category' => 'Clothing',
                'stock' => 40,
                'featured' => false,
                'sku' => 'CLO-001',
                'weight' => 0.2,
                'dimensions' => ['length' => 70, 'width' => 50, 'height' => 5],
                'brand' => 'BikeYard',
                'model' => 'Performance',
                'year' => 2024,
                'condition' => 'new',
                'warranty' => '30 days',
                'shipping_info' => 'Standard shipping',
            ],
            [
                'name' => 'Bike Lights Set',
                'description' => 'LED bike lights set with front and rear lights. USB rechargeable with long battery life.',
                'price' => 39.99,
                'images' => ['/products/Accessories.png'],
                'category' => 'Accessories',
                'stock' => 35,
                'featured' => false,
                'sku' => 'ACC-005',
                'weight' => 0.3,
                'dimensions' => ['length' => 15, 'width' => 10, 'height' => 5],
                'brand' => 'BikeYard',
                'model' => 'LED Pro',
                'year' => 2024,
                'condition' => 'new',
                'warranty' => '1 year',
                'shipping_info' => 'Standard shipping',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
